apiVersion: v2
name: ezldap
description: ezLDAP - easy read access for LDAP
type: application
version: 1.0.6
appVersion: "1.1.0"
maintainers:
  - name: eidottermihi
    email: eidottermihi@gmail.com
home: https://github.com/it-at-m/helm-charts/tree/main/charts/ezldap
icon: ../../images/logo.png
sources:
  - "https://github.com/it-at-m/helm-charts"
