apiVersion: v2
name: ezldap
description: ezLDAP - easy read access for LDAP
type: application
version: 1.0.1
appVersion: "v1.0.0"
maintainers:
  - name: Michael Prankl
    email: eidottermihi@gmail.com
home: https://github.com/it-at-m/helm-charts/tree/main/charts/ezldap
icon: https://opensource.muenchen.de/assets/itm-logo-256.png
sources:
  - "https://github.com/it-at-m/helm-charts"
