{{- $dot := . }}
{{- range $moduleName, $module := .Values.modules -}}
{{ $data := dict "dot" $dot "module" $module "moduleName" $moduleName }}
{{ if $module.applicationYML }}
{{ $checksum := $module.applicationYML | toYaml | sha256sum | trunc 64 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "getFullname" $data }}-application-yml
  labels:
    {{- include "getLabels" $data | trim | nindent 4 }}
  annotations:
    checksum/config: {{ $checksum }}
data:
  {{- with $module.applicationYML }}
  application.yml: |
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
