{{- $dot := . }}
{{- range $moduleName, $module := .Values.modules -}}
{{ $data := dict "dot" $dot "module" $module "moduleName" $moduleName }}
{{- if and  $module.serviceMonitor $module.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "getLabels" $data | trim | nindent 4 }}
  name: {{ include "getFullname" $data }}
spec:
  endpoints:
    - interval: {{ $module.serviceMonitor.interval | default "30s" }}
      path: {{ $module.serviceMonitor.path | default "/actuator/metrics" }}
      port: {{ $module.serviceMonitor.port | default "http" }}
      scheme: {{ $module.serviceMonitor.scheme | default "http" }}
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace }}
  selector:
    matchLabels:
      {{- include "getLabels" $data | trim | nindent 6 }}
{{- end }}
{{- end }}
