apiVersion: v2
name: refarch-templates
description: Helm Chart for deploying a it@M Reference Architecture application.
type: application
version: 1.0.0
home: https://github.com/it-at-m/helm-charts/tree/main/charts/refarch-templates
icon: https://assets.muenchen.de/logos/itm/itm-logo-256.png
sources:
  - "https://github.com/it-at-m/helm-charts"
maintainers:
  - name: devtobi
    url: https://github.com/devtobi
  - name: simonhir
    url: https://github.com/simonhir
  - name: DanielOber
    url: https://github.com/DanielOber
  - name: langehm
    url: https://github.com/langehm
