apiVersion: v2
name: sps-sample
description: Helm Chart for deploying a it@M Reference Architecture based sample application.
type: application
version: 1.0.5
home: https://github.com/it-at-m/helm-charts/tree/main/charts/sps-sample
icon: https://assets.muenchen.de/logos/itm/itm-logo-256.png
sources:
  - "https://github.com/it-at-m/helm-charts"
dependencies:
  - name: backend
    version: 1.0.0
  - name: frontend
    version: 1.0.0
  - name: refarch-gateway
    version: ^1.0.0
    repository: "@it-at-m"
  - name: postgresql
    version: 16.4.14
    repository: https://charts.bitnami.com/bitnami
    condition: database.enabled
    alias: database
  - name: keycloak
    version: 24.4.10
    repository: https://charts.bitnami.com/bitnami
    condition: keycloak.enabled
  - name: appswitcher-server
    version: 1.2.2
    repository: "@it-at-m"
    condition: appswitcher-server.enabled
maintainers:
  - name: banzuu
    url: https://github.com/banzuu
  - name: hupling
    url: https://github.com/hupling
  - name: ejcsid
    url: https://github.com/ejcsid
