apiVersion: v2
name: kf-app-eai
description: Enterprise application interface to allow Munich's kita-app access to kitafinder data.
type: application
version: 0.1.4
appVersion: "1.0.2"
maintainers:
  - name: maximilian-zollbrecht
    email: max.zollbrecht@gmail.com
home: https://github.com/it-at-m/helm-charts/tree/main/charts/kf-app-eai
icon: https://assets.muenchen.de/logos/itm/itM_Basislogo_gelb_schwarz-256.png
sources:
  - "https://github.com/it-at-m/helm-charts"
