apiVersion: v2
name: frontend
description: DAVe traffic counting plattform, frontend
type: application
version: 0.1.0
appVersion: "2.1.1"
maintainers:
  - name: klml
    email: klml@muenchen.de
home: https://github.com/it-at-m/helm-charts/tree/main/charts/dave/charts/frontend
#icon: https://raw.githubusercontent.com/it-at-m/helm-charts/main/images/logo.png
sources:
  - "https://github.com/it-at-m/helm-charts"
  - "https://github.com/it-at-m/dave-frontend"
