apiVersion: v2
name: ad2image
description: "easy avatars powered by AD / Exchange & Identicons"
type: application
version: 1.2.6
appVersion: "1.2.0"
maintainers:
  - name: eidottermihi
    email: eidottermihi@gmail.com
home: https://github.com/it-at-m/helm-charts/tree/main/charts/ad2image
icon: https://raw.githubusercontent.com/it-at-m/helm-charts/main/images/logo.png
sources:
  - "https://github.com/it-at-m/helm-charts"
