apiVersion: v2
name: eai
description: DAVe traffic counting plattform, eai
type: application
version: 0.1.0
appVersion: "2.1.1"
maintainers:
  - name: gislab-augsburg
    email: martymcfly333@gmail.com
  - name: klml
    email: klml@muenchen.de
home: https://github.com/it-at-m/helm-charts/tree/main/charts/dave/charts/eai
icon: https://raw.githubusercontent.com/it-at-m/helm-charts/main/images/logo.png
sources:
  - "https://github.com/it-at-m/helm-charts"
  - "https://github.com/it-at-m/dave-eai"
