apiVersion: v2
name: eai
description: DAVe traffic counting plattform, eai
type: application
version: 0.0.1
appVersion: "v1.0.0"
maintainers:
  - name: gislab-augsburg
    email: martymcfly333@gmail.com
  - name: klml
    email: klml@muenchen.de
home: https://github.com/it-at-m/helm-charts/tree/main/charts/dave/charts/eai
#icon: https://opensource.muenchen.de/assets/itm-logo-256.png
sources:
  - "https://github.com/it-at-m/helm-charts"
  - "https://github.com/it-at-m/dave-eai"
