apiVersion: v1
kind: Secret
metadata:
  name: {{ include "daveDocumentStorage.fullname" . }}-secret
  labels: 
    {{- include "daveDocumentStorage.labels" . | nindent 4 }}
stringData:
  {{- with .Values.credentials }}
    {{- toYaml . | nindent 12 }}
  {{- end}}