apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "daveGeodataEai.fullname" . }}
  labels: 
    {{- include "daveGeodataEai.labels" . | nindent 4 }}
data:
  {{- with .Values.extraEnvVars.env }}
    {{- toYaml . | nindent 12 }}
  {{- end}}
