apiVersion: v1
kind: Secret
metadata:
  name: {{ include "daveGeodataEai.fullname" . }}-secret
  labels: 
    {{- include "daveGeodataEai.labels" . | nindent 4 }}
stringData:
  {{- with .Values.credentials }}
    {{- toYaml . | nindent 12 }}
  {{- end}}