apiVersion: v2
name: refarch-gateway
description: Helm chart for deploying the it@M refarch-gateway
type: application
version: 1.1.3
appVersion: 1.1.2
home: https://github.com/it-at-m/helm-charts/tree/main/charts/refarch-gateway
icon: https://opensource.muenchen.de/assets/itm-logo-256.png
sources:
  - "https://github.com/it-at-m/helm-charts"
maintainers:
  - name: DanielOber
    url: https://github.com/DanielOber
  - name: devtobi
    url: https://github.com/devtobi
  - name: simonhir
    url: https://github.com/simonhir
