apiVersion: v2
name: refarch-gateway
description: Helm chart for deploying the it@M refarch-gateway
type: application
version: 1.5.1
appVersion: 1.5.0
home: https://github.com/it-at-m/helm-charts/tree/main/charts/refarch-gateway
icon: https://assets.muenchen.de/logos/itm/itm-logo-256.png
sources:
  - "https://github.com/it-at-m/helm-charts"
maintainers:
  - name: DanielOber
    url: https://github.com/DanielOber
  - name: devtobi
    url: https://github.com/devtobi
  - name: simonhir
    url: https://github.com/simonhir
