apiVersion: v2
name: backend
description: DAVe traffic counting plattform, backend
type: application
version: 0.1.3
appVersion: "3.0.0"
maintainers:
  - name: klml
    email: klml@muenchen.de
home: https://github.com/it-at-m/helm-charts/tree/main/charts/dave/charts/backend
#icon: https://raw.githubusercontent.com/it-at-m/helm-charts/main/images/logo.png
sources:
  - "https://github.com/it-at-m/helm-charts"
  - "https://github.com/it-at-m/dave-backend-postgres"
