apiVersion: v2
name: backend
description: DAVe traffic counting plattform, backend
type: application
version: 0.0.3
appVersion: "v1.0.0"
maintainers:
  - name: gislab-augsburg
    email: martymcfly333@gmail.com
  - name: klml
    email: klml@muenchen.de
home: https://github.com/it-at-m/helm-charts/tree/main/charts/dave/charts/backend
#icon: https://assets.muenchen.de/logos/itm/itM_Basislogo_gelb_schwarz-256.png
sources:
  - "https://github.com/it-at-m/helm-charts"
  - "https://github.com/it-at-m/dave-backend-postgres"
