apiVersion: v2
name: java-spring-boot
description: Generic Helm chart to deploy a Spring Boot application on Kubernetes
type: application
version: 0.3.1
maintainers:
  - name: eidottermihi
    email: eidottermihi@gmail.com
home: https://github.com/it-at-m/helm-charts/tree/main/charts/java-spring-boot
icon: https://assets.muenchen.de/logos/itm/itM_Basislogo_gelb_schwarz-256.png
sources:
  - "https://github.com/it-at-m/helm-charts"
