apiVersion: v2
name: appswitcher-server
description: Server component for a Google-like app switching experience.
type: application
version: 1.2.6
appVersion: "1.3.0"
maintainers:
  - name: eidottermihi
    email: eidottermihi@gmail.com
home: https://github.com/it-at-m/helm-charts/tree/main/charts/appswitcher-server
icon: https://assets.muenchen.de/logos/itm/itM_Basislogo_gelb_schwarz-256.png
sources:
  - "https://github.com/it-at-m/helm-charts"
