apiVersion: v2
name: appswitcher-server
description: Server component for a Google-like app switching experience.
type: application
version: 1.1.4
appVersion: "1.1.0"
maintainers:
  - name: eidottermihi
    email: eidottermihi@gmail.com
home: https://github.com/it-at-m/helm-charts/tree/main/charts/appswitcher-server
icon: https://opensource.muenchen.de/assets/itm-logo-256.png
sources:
  - "https://github.com/it-at-m/helm-charts"
