apiVersion: v2
name: appswitcher-server
description: Server component for a Google-like app switching experience.
type: application
version: 1.2.4
appVersion: "1.2.3"
maintainers:
  - name: eidottermihi
    email: eidottermihi@gmail.com
home: https://github.com/it-at-m/helm-charts/tree/main/charts/appswitcher-server
icon: https://assets.muenchen.de/logos/itm/itm-logo-256.png
sources:
  - "https://github.com/it-at-m/helm-charts"
