{{- $dot := . }}
{{- range $secret := .Values.secrets -}}
{{ $data := dict "dot" $dot "module" $secret }}
# Skip creation if the Secret exists
{{- if not (lookup "v1" "Secret" $dot.Release.Namespace $secret.name) }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $secret.name }}
  labels:
    {{- include "getLabels" $data | trim  | nindent 4 }}
  annotations:
    # Prevents deletion on helm uninstall
    helm.sh/resource-policy: keep
data:
  # The template creates Secrets with keys but no values, expecting them to be populated externally.
  {{- range $key := $secret.keys }}
  {{ $key }}:
  {{- end }}
{{- end }}
{{- end }}
