apiVersion: v2
name: document-storage
description: DAVe traffic counting platform, document-storage
type: application
version: 0.1.3
appVersion: "3.0.0"
maintainers:
  - name: klml
    email: klml@muenchen.de
home: https://github.com/it-at-m/helm-charts/tree/main/charts/dave/charts/document-storage
sources:
  - "https://github.com/it-at-m/helm-charts"
